# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget csirocsa csironn qsastime plplot plplotcxx plplotfortran mem null ps svg xfig xwin plfortrandemolib)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# The installation prefix configured by this project.
set(_IMPORT_PREFIX "/home/pi/plplot/install_directory")

# Create imported target csirocsa
add_library(csirocsa SHARED IMPORTED)

# Create imported target csironn
add_library(csironn SHARED IMPORTED)

# Create imported target qsastime
add_library(qsastime SHARED IMPORTED)

# Create imported target plplot
add_library(plplot SHARED IMPORTED)

# Create imported target plplotcxx
add_library(plplotcxx SHARED IMPORTED)

# Create imported target plplotfortran
add_library(plplotfortran SHARED IMPORTED)

# Create imported target mem
add_library(mem MODULE IMPORTED)

set_target_properties(mem PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot;/usr/lib/arm-linux-gnueabihf/libm.so"
)

# Create imported target null
add_library(null MODULE IMPORTED)

set_target_properties(null PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot;/usr/lib/arm-linux-gnueabihf/libm.so"
)

# Create imported target ps
add_library(ps MODULE IMPORTED)

set_target_properties(ps PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot;/usr/lib/arm-linux-gnueabihf/libm.so"
)

# Create imported target svg
add_library(svg MODULE IMPORTED)

set_target_properties(svg PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot;/usr/lib/arm-linux-gnueabihf/libm.so"
)

# Create imported target xfig
add_library(xfig MODULE IMPORTED)

set_target_properties(xfig PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot;/usr/lib/arm-linux-gnueabihf/libm.so"
)

# Create imported target xwin
add_library(xwin MODULE IMPORTED)

set_target_properties(xwin PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplot;/usr/lib/arm-linux-gnueabihf/libm.so;/usr/lib/arm-linux-gnueabihf/libSM.so;/usr/lib/arm-linux-gnueabihf/libICE.so;/usr/lib/arm-linux-gnueabihf/libX11.so;/usr/lib/arm-linux-gnueabihf/libXext.so;/usr/lib/arm-linux-gnueabihf/libpthread.so"
)

# Create imported target plfortrandemolib
add_library(plfortrandemolib STATIC IMPORTED)

set_target_properties(plfortrandemolib PROPERTIES
  INTERFACE_LINK_LIBRARIES "plplotfortran"
)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/export_plplot-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
