#include "rlab.h"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[420] =
    {   0,
       40,   40,   42,   42,   50,   50,   57,   57,    2,    2,
      114,  112,  113,    3,  112,  113,   80,  113,    4,  112,
      113,    5,  112,  113,    6,  112,  113,   92,  112,  113,
      112,  113,    9,  112,  113,  112,  113,   10,  112,  113,
      112,  113,   96,  112,  113,  112,  113,  112,  113,  112,
      113,  112,  113,  112,  113,   66,  112,  113,   66,  112,
      113,   66,  112,  113,   78,  112,  113,   90,  112,  113,
      112,  113,   88,  112,  113,   79,  112,  113,   76,  112,
      113,   76,  112,  113,  103,  112,  113,   76,  112,  113,
       76,  112,  113,   76,  112,  113,   76,  112,  113,   76,

      112,  113,   76,  112,  113,   76,  112,  113,   76,  112,
      113,   76,  112,  113,   76,  112,  113,   76,  112,  113,
       76,  112,  113,   76,  112,  113,   76,  112,  113,   76,
      112,  113,   76,  112,  113,  112,  113,   56,  103,  112,
      113,  113,    1,  113,  113,  113,   40,  113,   38,  113,
      113,16423,   42,  113,   47,  113,  113,   44,  113,   46,
      113,  113,   43,  113,   48,  113,   50,  113,   55,  113,
      113,   52,  113,   54,  113,  113,   51,  113,   57,  113,
       58,  113,   57,  113,    2,  113,    3,   80,   91,   77,
       36,   93,   83,   85,   81,   86,   82,  106,  101,  102,

       67,  104,  105,    7,    8,   84,  100,   66,   66,   66,
       63,   65,   71,   64,   66,   99,   97,   89,   95,   87,
       98,   76,   76,   76,   76,   76,   76,   76,   13,   76,
       76,   76,   76,   76,   76,   11,   76,   17,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   94,    1,   40,   38, 8231,16423,   42,   47,   44,
       46,   45,   43,   50,   55,   52,   54,   53,   51,   57,
       58,   57,    2,   67,   72,  111,  107,  108,   67,  109,
      110,   61,   68,   65,   64,   62,   34,   76,   76,   76,
       76,   76,   76,   76,   16,   76,   76,   76,   76,   76,

       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   45,   53,   59,   69,   60,   67,   71,   72,
       70,   68,   73,   76,   21,   76,   76,   76,   76,   12,
       76,   76,   76,   37,   76,   76,   76,   76,   33,   76,
       76,   76,   76,   76,   76,   76,   32,   76,   76,   76,
       37,   35,   69,   74,   69,   70,   70,   75,   18,   76,
       76,   76,   76,   76,   76,   25,   76,   76,   76,   76,
       76,   41,   76,   76,   76,   76,   15,   76,   14,   76,
       41,   69,   70,   74,   75,   76,   76,   76,   76,   26,
       76,   76,   30,   76,   76,   24,   76,   31,   76,   27,

       76,   20,   76,   76,   76,   22,   76,   76,   29,   76,
       49,   76,   49,   28,   76,   19,   76,   23,   76
    } ;

static yyconst flex_int16_t yy_accept[357] =
    {   0,
        1,    1,    1,    1,    1,    2,    3,    4,    5,    6,
        7,    8,    9,   10,   11,   12,   14,   17,   19,   22,
       25,   28,   31,   33,   36,   38,   41,   43,   46,   48,
       50,   52,   54,   56,   59,   62,   65,   68,   71,   73,
       76,   79,   82,   85,   88,   91,   94,   97,  100,  103,
      106,  109,  112,  115,  118,  121,  124,  127,  130,  133,
      136,  138,  142,  143,  145,  146,  147,  149,  151,  153,
      155,  157,  158,  160,  162,  163,  165,  167,  169,  171,
      172,  174,  176,  177,  179,  181,  183,  185,  187,  188,
      188,  188,  189,  189,  190,  190,  191,  191,  192,  192,

      193,  194,  195,  196,  197,  198,  199,  200,  200,  201,
      202,  203,  204,  205,  206,  207,  208,  209,  210,  211,
      211,  212,  213,  214,  215,  216,  217,  218,  219,  220,
      221,  222,  223,  224,  225,  226,  227,  228,  229,  231,
      232,  233,  234,  235,  236,  238,  240,  241,  242,  243,
      244,  245,  246,  247,  248,  249,  250,  251,  252,  253,
      253,  254,  254,  255,  256,  256,  257,  258,  259,  260,
      260,  261,  262,  263,  264,  265,  266,  266,  267,  268,
      269,  270,  271,  272,  273,  274,  274,  274,  274,  274,
      274,  274,  275,  275,  276,  277,  278,  278,  279,  280,

      280,  281,  282,  283,  283,  284,  285,  286,  287,  289,
      290,  291,  292,  293,  294,  295,  297,  298,  299,  300,
      301,  302,  303,  304,  305,  306,  307,  308,  309,  310,
      311,  312,  313,  314,  315,  315,  315,  315,  315,  315,
      316,  316,  316,  316,  317,  318,  318,  319,  319,  321,
      321,  322,  323,  324,  325,  327,  328,  329,  330,  332,
      333,  334,  336,  337,  338,  339,  341,  342,  343,  344,
      345,  346,  347,  349,  350,  351,  352,  352,  352,  353,
      353,  353,  354,  355,  355,  355,  357,  358,  359,  359,
      361,  362,  363,  364,  365,  366,  368,  369,  370,  371,

      372,  374,  375,  376,  377,  379,  381,  381,  382,  382,
      382,  384,  386,  386,  386,  386,  387,  388,  389,  390,
      392,  393,  395,  396,  398,  400,  402,  404,  404,  404,
      404,  404,  404,  404,  405,  406,  408,  409,  411,  413,
      414,  414,  414,  414,  414,  414,  416,  418,  420,  420,
      420,  420,  420,  420,  420,  420
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    5,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    7,    8,    9,   10,   11,   12,   13,    1,
        1,   14,   15,    1,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,   26,    1,   27,   28,   27,   27,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   33,   31,
       31,   31,   31,   31,   31,   31,   31,   34,   31,   31,
        1,   35,    1,   36,   37,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   47,   48,   49,   31,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       31,   31,    1,   61,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[62] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    4,    1,    5,    5,
        5,    1,    1,    1,    1,    1,    5,    5,    5,    5,
        6,    6,    6,    6,    1,    1,    6,    5,    5,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1
    } ;

static yyconst flex_uint16_t yy_base[375] =
    {   0,
        0,  809,   59,   60,   66,    0,  127,    0,  188,    0,
      247,  248,  840,  839,  841,  845,  250,  845,  845,  845,
      252,  816,  248,  845,  247,  845,  827,  845,  814,  244,
      245,  253,  261,  288,  243,  245,  845,  258,  813,  266,
      845,    0,  803,  845,  781,  249,  242,  785,  255,  784,
      790,  249,  780,  240,  773,  268,  273,  784,  778,  782,
      765,  845,  312,  845,  313,  845,  321,  845,  323,  823,
      845,  325,    0,    0,  806,    0,  845,  821,  845,  330,
        0,    0,  804,    0,    0,  845,  335,    0,  299,  779,
      297,  845,  339,  845,  319,  845,  817,  845,  777,  845,

      845,  845,  845,  845,  845,  845,  845,  801,  845,  330,
      845,  845,  845,  845,  845,  845,  365,  336,    0,  342,
      845,    0,  845,    0,  332,  845,  845,  845,  845,  845,
      845,    0,  787,  774,  760,  776,  763,  769,    0,  756,
      756,  759,  757,  758,    0,    0,  766,  759,  765,  754,
      290,  748,  734,  744,  727,  725,  702,  706,  845,  362,
      845,  363,  371,  845,  378,  845,  385,  708,  845,  364,
        0,    0,    0,    0,  707,  845,  386,    0,    0,    0,
        0,    0,  845,  387,    0,  659,  652,  658,  654,  393,
      383,  389,  400,  845,  845,  845,  685,  845,  405,  422,

      845,  845,  845,  408,  425,    0,    0,  845,    0,  663,
      656,  642,  640,  657,  652,    0,  653,  653,  639,  652,
      631,  639,  631,  626,  621,  622,  621,  610,  606,  611,
      598,  584,    0,    0,  580,  571,  573,  578,  411,  845,
      427,  436,  429,  441,  845,  444,  456,  480,  845,  447,
      459,  488,  845,  568,    0,  560,  563,  551,    0,  550,
      542,    0,  530,  534,  525,    0,  520,  507,  511,  492,
      490,  482,    0,  466,  469,  845,  458,  455,  845,  493,
      473,  499,  845,  504,  507,  512,  535,  845,  522,    0,
      448,  436,  435,  435,  425,    0,  414,  429,  405,  404,

        0,  384,  399,  387,    0,    0,  369,  845,  528,  543,
      548,  845,  554,  557,  565,  363,  341,  341,  340,    0,
      310,    0,  279,    0,    0,    0,    0,  272,  572,  578,
      581,  598,  605,  253,  238,    0,  228,    0,    0,  845,
      584,  610,  616,  619,  622,    0,    0,    0,  629,  644,
      653,  634,  660,  665,  845,  712,  718,  724,  730,  732,
      738,  743,  749,  755,  758,  764,  770,  773,  779,  785,
      255,   59,  791,  797
    } ;

static yyconst flex_int16_t yy_def[375] =
    {   0,
      355,    1,  356,  356,  355,    5,  355,    7,  355,    9,
      357,  357,  358,  358,  355,  355,  355,  355,  355,  355,
      355,  355,  359,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,   34,   35,  355,  355,  355,  355,
      355,  360,  360,  355,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      355,  355,  361,  355,  361,  355,  355,  355,  362,  355,
      355,  355,  363,  364,  355,  365,  355,  355,  355,  355,
      366,  367,  355,  368,  369,  355,  369,  370,  355,  355,
      355,  355,  355,  355,  359,  355,  359,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,   35,   36,  355,
      355,  371,  355,  372,   35,  355,  355,  355,  355,  355,
      355,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  355,  361,
      355,  361,  355,  355,  355,  355,  362,  355,  355,  355,
      363,  364,  373,  365,  355,  355,  355,  366,  367,  374,
      368,  369,  355,  369,  370,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  371,  372,  355,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  373,  374,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  355,  355,  355,
      355,  355,  355,  360,  360,  360,  360,  360,  360,  355,
      355,  355,  355,  355,  355,  360,  360,  360,  355,  355,
      355,  355,  355,  355,    0,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355
    } ;

static yyconst flex_uint16_t yy_nxt[907] =
    {   0,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   42,   43,   42,
       42,   42,   42,   42,   44,   16,   42,   42,   45,   46,
       47,   48,   49,   50,   51,   52,   42,   42,   53,   42,
       42,   54,   55,   56,   57,   58,   59,   42,   60,   42,
       61,   64,   64,  207,   65,   65,   66,   67,   68,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   69,   69,   69,   66,   66,   66,
       66,   66,   69,   69,   69,   69,   69,   69,   69,   69,

       66,   66,   66,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   66,   66,   70,   71,
       66,   66,   72,   66,   66,   73,   66,   74,   66,   66,
       66,   66,   66,   66,   75,   76,   76,   76,   77,   66,
       66,   66,   66,   76,   76,   76,   76,   76,   76,   76,
       76,   66,   66,   66,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   66,   66,   78,
       79,   66,   66,   80,   66,   66,   81,   66,   82,   66,

       66,   66,   66,   66,   66,   83,   84,   84,   84,   66,
       66,   66,   66,   66,   84,   84,   84,   84,   84,   84,
       84,   84,   66,   66,   66,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   66,   86,
       86,   89,   87,   87,   92,   96,   98,   93,  102,  206,
      104,  125,  125,  119,  119,  106,  107,  103,  105,  108,
      109,  110,  110,  110,  113,  126,  355,  348,  114,  347,
      127,  128,   97,  138,  115,  116,  135,  111,  112,  130,
      131,  145,  139,  148,   90,  346,  149,  136,  146,  137,

       89,   99,  355,   91,  117,  141,  118,  118,  119,  151,
      152,  142,  153,  340,  161,  161,  120,  162,  162,  121,
      339,  122,  163,  164,  165,  166,   96,  169,  154,  120,
      170,  155,  176,  123,  123,  177,  121,  183,  187,  188,
      184,   92,  224,   90,   93,  225,  191,  124,  192,  192,
      192,  338,   91,   97,  118,  118,  204,  204,  193,  208,
      205,  205,  205,  203,  161,  161,  169,  162,  162,  170,
      208,  193,  163,  164,  203,  194,  194,  195,  196,  165,
      166,  197,  198,  199,  199,  199,  165,  166,  176,  183,
      337,  177,  184,  200,  239,  240,  336,  335,  241,  201,

      202,  242,  242,  242,  334,  191,  200,  192,  192,  192,
      123,  123,  239,  240,  243,  243,  241,  193,  244,  244,
      244,  246,  328,  247,  247,  247,  205,  205,  205,  240,
      193,  327,  241,  248,  194,  194,  250,  250,  326,  325,
      251,  251,  251,  252,  252,  252,  248,  244,  244,  244,
      249,  249,  191,  324,  280,  280,  280,  281,  323,  282,
      282,  282,  284,  284,  284,  251,  251,  251,  322,  321,
      253,  253,  246,  320,  247,  247,  247,  287,  287,  287,
      319,  194,  194,  318,  248,  317,  283,  283,  316,  123,
      123,  309,  309,  309,  285,  285,  308,  248,  286,  286,

      286,  249,  249,  307,  288,  288,  252,  252,  252,  191,
      306,  280,  280,  280,  305,  281,  289,  282,  282,  282,
      246,  304,  310,  310,  310,  286,  286,  286,  281,  289,
      311,  311,  311,  253,  253,  303,  314,  314,  194,  194,
      315,  315,  315,  302,  283,  283,  309,  309,  309,  249,
      249,  313,  301,  287,  287,  287,  329,  312,  312,  246,
      300,  310,  310,  310,  330,  299,  311,  311,  311,  329,
      298,  297,  331,  331,  331,  315,  315,  315,  296,  295,
      288,  288,  332,  333,  333,  333,  341,  341,  249,  249,
      342,  342,  342,  312,  312,  332,  343,  343,  343,  331,

      331,  331,  342,  342,  342,  294,  332,  293,  292,  332,
      253,  253,  344,  344,  291,  290,  345,  345,  345,  332,
      279,  278,  332,  333,  333,  333,  281,  277,  349,  349,
      349,  276,  275,  289,  343,  343,  343,  345,  345,  345,
      351,  351,  351,  274,  350,  281,  289,  349,  349,  349,
      253,  253,  353,  353,  353,  283,  283,  350,  352,  352,
      273,  272,  353,  353,  353,  271,  270,  288,  288,  313,
      269,  351,  351,  351,  283,  283,  281,  268,  354,  354,
      354,  330,  267,  354,  354,  354,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  255,  288,  288,

      254,  245,  238,  237,  236,  312,  312,  235,  175,  168,
      312,  312,   63,   63,   63,   63,   63,   63,   85,   85,
       85,   85,   85,   85,   88,   88,   88,   88,   88,   88,
       95,   95,   95,   95,   95,   95,  132,  132,  160,  160,
      160,  160,  160,  160,  167,  167,  167,  167,  167,  171,
      171,  232,  171,  171,  171,  172,  172,  231,  172,  172,
      172,  174,  174,  174,  178,  178,  230,  178,  178,  178,
      179,  179,  229,  179,  179,  179,  181,  181,  181,  182,
      182,  228,  182,  182,  182,  185,  185,  227,  185,  185,
      185,  233,  233,  226,  233,  233,  233,  234,  234,  223,

      234,  234,  234,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  190,  189,  355,
      186,  180,  175,  173,  168,  159,  158,  157,  156,  150,
      147,  144,  143,  140,  134,  133,  129,  101,  100,   94,
      355,   66,   66,   62,   15,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355
    } ;

static yyconst flex_int16_t yy_chk[907] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,  372,    3,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,   11,
       12,   17,   11,   12,   21,   23,   25,   21,   30,  371,
       31,   35,   35,   36,   36,   32,   32,   30,   31,   32,
       32,   32,   32,   32,   33,   38,   35,  337,   33,  335,
       38,   38,   23,   47,   33,   33,   46,   32,   32,   40,
       40,   52,   47,   54,   17,  334,   54,   46,   52,   46,

       89,   25,   35,   17,   34,   49,   34,   34,   34,   56,
       56,   49,   57,  328,   63,   65,   34,   63,   65,   34,
      323,   34,   67,   67,   69,   69,   95,   72,   57,   34,
       72,   57,   80,   34,   34,   80,   34,   87,   91,   91,
       87,   93,  151,   89,   93,  151,  110,   34,  110,  110,
      110,  321,   89,   95,  118,  118,  120,  120,  110,  125,
      120,  120,  120,  118,  160,  162,  170,  160,  162,  170,
      125,  110,  163,  163,  118,  110,  110,  117,  117,  165,
      165,  117,  117,  117,  117,  117,  167,  167,  177,  184,
      319,  177,  184,  117,  190,  190,  318,  317,  190,  117,

      117,  191,  191,  191,  316,  192,  117,  192,  192,  192,
      117,  117,  239,  239,  193,  193,  239,  192,  193,  193,
      193,  199,  307,  199,  199,  199,  204,  204,  204,  241,
      192,  304,  241,  199,  192,  192,  200,  200,  303,  302,
      200,  200,  200,  205,  205,  205,  199,  243,  243,  243,
      199,  199,  242,  300,  242,  242,  242,  244,  299,  244,
      244,  244,  246,  246,  246,  250,  250,  250,  298,  297,
      205,  205,  247,  295,  247,  247,  247,  251,  251,  251,
      294,  242,  242,  293,  247,  292,  244,  244,  291,  246,
      246,  281,  281,  281,  248,  248,  278,  247,  248,  248,

      248,  247,  247,  277,  251,  251,  252,  252,  252,  280,
      275,  280,  280,  280,  274,  282,  252,  282,  282,  282,
      284,  272,  284,  284,  284,  285,  285,  285,  286,  252,
      286,  286,  286,  252,  252,  271,  289,  289,  280,  280,
      289,  289,  289,  270,  282,  282,  309,  309,  309,  284,
      284,  287,  269,  287,  287,  287,  309,  286,  286,  310,
      268,  310,  310,  310,  311,  267,  311,  311,  311,  309,
      265,  264,  313,  313,  313,  314,  314,  314,  263,  261,
      287,  287,  313,  315,  315,  315,  329,  329,  310,  310,
      329,  329,  329,  311,  311,  313,  330,  330,  330,  331,

      331,  331,  341,  341,  341,  260,  330,  258,  257,  331,
      315,  315,  332,  332,  256,  254,  332,  332,  332,  330,
      238,  237,  331,  333,  333,  333,  342,  236,  342,  342,
      342,  235,  232,  333,  343,  343,  343,  344,  344,  344,
      345,  345,  345,  231,  343,  349,  333,  349,  349,  349,
      333,  333,  352,  352,  352,  342,  342,  343,  350,  350,
      230,  229,  350,  350,  350,  228,  227,  345,  345,  351,
      226,  351,  351,  351,  349,  349,  353,  225,  353,  353,
      353,  354,  224,  354,  354,  354,  223,  222,  221,  220,
      219,  218,  217,  215,  214,  213,  212,  211,  351,  351,

      210,  197,  189,  188,  187,  353,  353,  186,  175,  168,
      354,  354,  356,  356,  356,  356,  356,  356,  357,  357,
      357,  357,  357,  357,  358,  358,  358,  358,  358,  358,
      359,  359,  359,  359,  359,  359,  360,  360,  361,  361,
      361,  361,  361,  361,  362,  362,  362,  362,  362,  363,
      363,  158,  363,  363,  363,  364,  364,  157,  364,  364,
      364,  365,  365,  365,  366,  366,  156,  366,  366,  366,
      367,  367,  155,  367,  367,  367,  368,  368,  368,  369,
      369,  154,  369,  369,  369,  370,  370,  153,  370,  370,
      370,  373,  373,  152,  373,  373,  373,  374,  374,  150,

      374,  374,  374,  149,  148,  147,  144,  143,  142,  141,
      140,  138,  137,  136,  135,  134,  133,  108,   99,   97,
       90,   83,   78,   75,   70,   61,   60,   59,   58,   55,
       53,   51,   50,   48,   45,   43,   39,   29,   27,   22,
       15,   14,   13,    2,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
/* scan.l */
/*  This file is a part of RLaB ("Our"-LaB)
    Copyright (C) 1992, 1993, 1994  Ian R. Searle
    Copyright (C) 2015-2016 M. Kostrun

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

    See the file ./COPYING
 ***********************************************************************/
#include "rlab.h"
#include "code.h"
#include "y.tab.h"
#include "list.h"
#include "util.h"
#include "mem.h"
#include "bltin.h"
#include "print.h"
#include "rfileio.h"

#include <stdio.h>
#include <string.h>
#include <errno.h>

#ifndef FOPEN_MAX
#define FOPEN_MAX 20
#endif

#ifdef titan
extern double strtod ();
#endif

#undef  THIS_FILE
#define THIS_FILE "scan.l"

extern int flush_line;                 /* rlab.y */
static char dummy_line[] = "DUMMY \n"; /* Dummy string */
int lineno = 0;                        /* Keep track of line numbers */
char *curr_file_name = 0;              /* Keep track of the current file */

char *line_contents = 0;               /* For getting at current line */
extern int use_readline;               /* From main.c */
extern void intcatch_wait (int);       /* main.c */

char *rm_escape (char *s);
int   count_eol (char *s);

extern int read_script;
char newclass_def[65536] = {'\0'};
int newclass_count_curly_braces=0;

extern int Rlab_Debug;

/*
 * The two ways RLaB can get its input for the scanner.
 */

typedef void (*RINPUT) ();
RINPUT rinput;   /* Point this at the correct input function. */

void rlab_yy_input     (char *buf, int *result, int *max_size);
void rlab_string_input (char *buf, int *result, int *max_size);
void set_rlab_input (int type);

#undef YY_INPUT
#define YY_INPUT(buf, result, max_size) \
        (*rinput) (buf, &(result), &(max_size))

#undef yywrap
int yywrap (void);
int new_file (char *file_name);

/* Prompt info */
extern int prompt;               /* From rlab.y */
static char prompt1[] = ">> ";    /* Use when prompt == 0, by Marijan Kostrun, just like M*tlab */
static char prompt2[] = "  ";    /* Use when prompt > 0 */

static char *endp;

#define INITIAL 0
#define FLUSH 1
#define HELP_COND 2
#define RFILE_COND 3
#define REQ_COND 4
#define SYS_COND 5
#define RLABSCRIPT 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{

  /* Always check flush_line */
  if(flush_line)
  {
    BEGIN FLUSH;
  }
  if(read_script)
  {
    BEGIN RLABSCRIPT;
  }

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 356 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 845 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
{
                /* Eat up the rest of the input line */
                flush_line = 0;
                BEGIN 0; lineno++;
                return '\n';
              }
	YY_BREAK
/* SCRIPT command */
case 2:
YY_RULE_SETUP
{
                  newclass_def[0] = '\0';
                  newclass_count_curly_braces = 1;
                  int len = 0, k;
                  unsigned char c;
                  while (1)
                  {
                    c = input();
                    if (c == '\n')
                    {
                      ++lineno;
                      if (len)
                      {
                        k = len;
                        while (k--)
                        {
                          if ((newclass_def[k] == ' ')||(newclass_def[k] == '\t'))
                          {
                            len--;
                            continue;
                          }
                          break;
                        }
                      }
                      else
                        continue;
                    }
                    newclass_def[len++] = c;
                    if (c == '{')
                    {
                      newclass_count_curly_braces++;
                    }
                    else if (c == '}')
                    {
                      newclass_count_curly_braces--;
                      if (!newclass_count_curly_braces)
                      {
                        newclass_def[--len] = '\0'; /* ignore closing right curly brace */
                        while(newclass_def[--len]=='\n'){;}
                          newclass_def[++len] = '\0';
                        yylval.name = cpstr(newclass_def);
                        BEGIN(INITIAL);
                        read_script = 0;
                        return R_SCRIPT;
                      }
                    }
                  }
                }
	YY_BREAK
/* skip blanks and tabs */
case 3:
YY_RULE_SETUP
{ ; }
	YY_BREAK
/* skip some control characters */
case 4:
YY_RULE_SETUP
{ /* \f  return */ ; }
	YY_BREAK
case 5:
YY_RULE_SETUP
{ /* \f  form-feed */ ; }
	YY_BREAK
case 6:
YY_RULE_SETUP
{ /* \f  return    */ ; }
	YY_BREAK
/* what is thy comment? 2016-09-22 */
/* Recognize comments C-style. No memory leaks. Don't get angry if luser forgets to terminate comment */
case 7:
YY_RULE_SETUP
{
          unsigned char c1=0, c2=input();
          while(1)
          {
            if (c2==0xff)
            {
              printf ("WARNING: File ended with unterminated comment in Line %i\n", lineno);
              break;
            }
            if (c2=='/' && c1=='*')
              break;
            if (c2=='\n')
              ++lineno;
            c1 = c2;
            c2 = input();
          }
          BEGIN(INITIAL);
          if(c2 == 0xff)
          {
            unput(c2);
          }
          return '\n';
        }
	YY_BREAK
/* Recognize comments: C++, Matlab, shell. */
/* "//".*\n   { lineno++; } */
/* "#".*\n    { lineno++; } */
/* "%".*\n    { lineno++; } */
/* what is thy comment? 2016-09-22: No memory leaks for files ending with comment line */
case 8:
case 9:
case 10:
YY_RULE_SETUP
{
          unsigned char c;
          while (1)
          {
            c = input();
            if (c=='\n')
            {
              ++lineno;
              break;
            }
            if (c==0xff)
            {
              break;
            }
          }
          /* Maybe you want to place back EOF? It is processed at the end of the scanner */
          BEGIN(INITIAL);
          if(c == 0xff)
          {
            unput(c);
          }
          return '\n';
        }
	YY_BREAK
/* recognize keywords */
case 11:
YY_RULE_SETUP
return IF;
	YY_BREAK
case 12:
YY_RULE_SETUP
return ELSE;
	YY_BREAK
case 13:
YY_RULE_SETUP
return DO;
	YY_BREAK
case 14:
YY_RULE_SETUP
return WHILE;
	YY_BREAK
case 15:
YY_RULE_SETUP
return UNTIL;
	YY_BREAK
case 16:
YY_RULE_SETUP
return FOR;
	YY_BREAK
case 17:
YY_RULE_SETUP
return IN;
	YY_BREAK
case 18:
YY_RULE_SETUP
return BREAK;
	YY_BREAK
case 19:
YY_RULE_SETUP
return CONTINUE;
	YY_BREAK
case 20:
YY_RULE_SETUP
return SWITCH;
	YY_BREAK
case 21:
YY_RULE_SETUP
return SWITCH_CASE;
	YY_BREAK
case 22:
YY_RULE_SETUP
return SWITCH_DEFAULT;
	YY_BREAK
case 23:
YY_RULE_SETUP
return FUNCTION;
	YY_BREAK
case 24:
YY_RULE_SETUP
return RETURN;
	YY_BREAK
case 25:
YY_RULE_SETUP
return LOCAL_DEC;
	YY_BREAK
case 26:
YY_RULE_SETUP
return GLOBAL_DEC;
	YY_BREAK
case 27:
YY_RULE_SETUP
return FSTATIC_DEC;
	YY_BREAK
case 28:
YY_RULE_SETUP
return CLASSDEF;
	YY_BREAK
case 29:
YY_RULE_SETUP
return CLASS_PRIV;
	YY_BREAK
case 30:
YY_RULE_SETUP
return CLASS_PUBL;
	YY_BREAK
case 31:
YY_RULE_SETUP
return RSCRIPT_DEC;
	YY_BREAK
case 32:
YY_RULE_SETUP
return LOOPTHEN;
	YY_BREAK
case 33:
YY_RULE_SETUP
return QUIT;
	YY_BREAK
case 34:
YY_RULE_SETUP
return ENDFILE;
	YY_BREAK
case 35:
YY_RULE_SETUP
return SELF;
	YY_BREAK
case 36:
YY_RULE_SETUP
return GST;
	YY_BREAK
/* Special keywords/commands */
/* HELP cmd*/
case 37:
YY_RULE_SETUP
{ BEGIN HELP_COND; }
	YY_BREAK
case 38:
/* rule 38 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{ BEGIN 0; lineno++; return HELP; }
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
{ yylval.name = cpstr(yytext); BEGIN 0; lineno++; return HELP_NAME; }
	YY_BREAK
case 40:
YY_RULE_SETUP
{ ; }
	YY_BREAK
/* rfile filename1 filename2 ... */
case 41:
YY_RULE_SETUP
{ BEGIN RFILE_COND; return RFILE; }
	YY_BREAK
/* Handle blanks and tabs. */
case 42:
YY_RULE_SETUP
{ ; }
	YY_BREAK
/* Multiple file names. */
case 43:
YY_RULE_SETUP
{ yylval.name = cpstr (yytext); return FNAME; }
	YY_BREAK
/* Handle coments on the same line. */
case 44:
YY_RULE_SETUP
{ ; }
	YY_BREAK
case 45:
YY_RULE_SETUP
{ ; }
	YY_BREAK
case 46:
YY_RULE_SETUP
{ ; }
	YY_BREAK
/* End of special rfile handling. */
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
{ BEGIN 0; lineno++; return '\n'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
{ BEGIN 0; return '\n'; }
	YY_BREAK
/* The require command. */
case 49:
YY_RULE_SETUP
{ BEGIN REQ_COND; return REQUIRE; }
	YY_BREAK
/* Handle blanks and tabs. */
case 50:
YY_RULE_SETUP
{ ; }
	YY_BREAK
/* Multiple file names. */
case 51:
YY_RULE_SETUP
{ yylval.name = cpstr (yytext); return FNAME; }
	YY_BREAK
/* Handle coments on the same line. */
case 52:
YY_RULE_SETUP
{ ; }
	YY_BREAK
case 53:
YY_RULE_SETUP
{ ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
{ ; }
	YY_BREAK
/* End of special rfile handling. */
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
{ BEGIN 0; lineno++; return '\n'; }
	YY_BREAK
/* The system (\) command. */
/* We must do this here because of the LDIV operator. */
case 56:
YY_RULE_SETUP
{ BEGIN SYS_COND; }
	YY_BREAK
case 57:
YY_RULE_SETUP
{ yylval.name = cpstr(yytext); return SYS_CMD; }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
{ BEGIN 0; lineno++; return '\n'; }
	YY_BREAK
/* continuation characters */
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
{ lineno++; }
	YY_BREAK
case 60:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{
                      sscanf(yytext, "%lf", &(yylval.d_val));
                      return NUMBER;
                   }
	YY_BREAK
/* read in bit numbers: kmk IV-2015*/
case 61:
case 62:
YY_RULE_SETUP
{
                    register int _n = strtod (yytext, (char **) &endp);
                    register int _d = 1;
                    register int _r = _n % 10;
                    while (_n)
                    {
                      _d  = 2 * _d;
                      _n  = _n / 10;
                      _r += (_n % 10) * _d;
                    }
                    yylval.d_val = _r;
                    return INTEGER;
                  }
	YY_BREAK
/* read in integers as ending with l/L or in hex format - prepended 0x/0X - kmk III-2015*/
case 63:
case 64:
case 65:
YY_RULE_SETUP
{
                    yylval.d_val = strtod (yytext, (char **) &endp);
                    return INTEGER;
                  }
	YY_BREAK
/* read in real numbers */
case 66:
case 67:
case 68:
YY_RULE_SETUP
{
                       errno = 0;
                       yylval.d_val = strtod (yytext, (char **) &endp);
                       if (errno)
                         warning_1 ("decimal over/under flow problem");
                       return NUMBER; }
	YY_BREAK
case 69:
YY_RULE_SETUP
{
                       errno = 0;
                       yylval.d_val = strtod (yytext, (char **) &endp);
                       if (errno)
                         warning_1 ("decimal over/under flow problem");
                       return NUMBER; }
	YY_BREAK
case 70:
YY_RULE_SETUP
{
                       errno = 0;
                       yylval.d_val = strtod (yytext, (char **) &endp);
                       if (errno)
                         warning_1 ("decimal over/under flow problem");
                       return NUMBER; }
	YY_BREAK
/* read complex constants */
case 71:
case 72:
case 73:
YY_RULE_SETUP
{
                       errno = 0;
                       yylval.d_val = strtod (yytext, (char **) &endp);
                       if (errno)
                         warning_1 ("decimal over/under flow problem");
                       return iNUMBER; }
	YY_BREAK
case 74:
YY_RULE_SETUP
{
                       errno = 0;
                       yylval.d_val = strtod (yytext, (char **) &endp);
                       if (errno)
                         warning_1 ("decimal over/under flow problem");
                       return iNUMBER; }
	YY_BREAK
case 75:
YY_RULE_SETUP
{
                       errno = 0;
                       yylval.d_val = strtod (yytext, (char **) &endp);
                       if (errno)
                         warning_1 ("decimal over/under flow problem");
                       return iNUMBER; }
	YY_BREAK
/* read in variables, function names, whatever */
case 76:
YY_RULE_SETUP
{ yylval.name = cpstr(yytext); return(NAME); }
	YY_BREAK
/* get character strings enclosed in " " \"([^\\\"\n]|\\.)*\" */
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
{
    yylval.name = cpstr_strip(yytext);
    rm_escape(yylval.name);
    lineno+=count_eol(yylval.name);
    return(R_STRING);
                    }
	YY_BREAK
/* read in semicolons, through away newline if it follows a ';'
    or a '?'. We have to do this because the parser interprets
    '\n', ';', '?' as end-of-statement. If we sent ;\n to the
    parser it would interpret it a one valid statement and one
    null statement. */
case 78:
YY_RULE_SETUP
{ return SEMIC; }
	YY_BREAK
case 79:
YY_RULE_SETUP
{ return Q_MARK; }
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
{ lineno++; return '\n'; }
	YY_BREAK
/* read in special operators */
case 81:
YY_RULE_SETUP
{ return ADDTO; }
	YY_BREAK
case 82:
YY_RULE_SETUP
{ return SUBFROM; }
	YY_BREAK
case 83:
YY_RULE_SETUP
{ return EL_MUL_BY; }
	YY_BREAK
case 84:
YY_RULE_SETUP
{ return EL_DIV_BY; }
	YY_BREAK
case 85:
YY_RULE_SETUP
{ return INC; }
	YY_BREAK
case 86:
YY_RULE_SETUP
{ return DEC; }
	YY_BREAK
case 87:
YY_RULE_SETUP
{ return GE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
{ return GT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
{ return LE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
{ return LT; }
	YY_BREAK
case 91:
YY_RULE_SETUP
{ return NE; }
	YY_BREAK
case 92:
YY_RULE_SETUP
{ return NOT; }
	YY_BREAK
case 93:
YY_RULE_SETUP
{ return AND; }
	YY_BREAK
case 94:
YY_RULE_SETUP
{ return OR; }
	YY_BREAK
case 95:
YY_RULE_SETUP
{ return EQ; }
	YY_BREAK
case 96:
YY_RULE_SETUP
{ return TRANSPOSE; }
	YY_BREAK
case 97:
YY_RULE_SETUP
{ return LEFT_LIST; }
	YY_BREAK
case 98:
YY_RULE_SETUP
{ return RIGHT_LIST; }
	YY_BREAK
case 99:
YY_RULE_SETUP
{ return L_OLIST; }
	YY_BREAK
case 100:
YY_RULE_SETUP
{ return R_OLIST; }
	YY_BREAK
case 101:
YY_RULE_SETUP
{ return EL_MUL_OP; }
	YY_BREAK
case 102:
YY_RULE_SETUP
{ return EL_DIV_OP; }
	YY_BREAK
case 103:
YY_RULE_SETUP
{ return LDIV_OP; }
	YY_BREAK
case 104:
YY_RULE_SETUP
{ return EL_LDIV_OP; }
	YY_BREAK
case 105:
YY_RULE_SETUP
{ return EL_POW_OP; }
	YY_BREAK
case 106:
YY_RULE_SETUP
{ return EL_TRANSPOSE; }
	YY_BREAK
/* Handle special conditions: such as 3./A */
case 107:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{
                      sscanf(yytext, "%lf", &(yylval.d_val));
                      return NUMBER;
                  }
	YY_BREAK
case 108:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{
                      sscanf(yytext, "%lf", &(yylval.d_val));
                      return NUMBER;
                  }
	YY_BREAK
case 109:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{
                      sscanf(yytext, "%lf", &(yylval.d_val));
                      return NUMBER;
                   }
	YY_BREAK
case 110:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{
                      sscanf(yytext, "%lf", &(yylval.d_val));
                      return NUMBER;
                  }
	YY_BREAK
case 111:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
{
                      sscanf(yytext, "%lf", &(yylval.d_val));
                      return NUMBER;
                  }
	YY_BREAK
case 112:
YY_RULE_SETUP
{ return yytext[0]; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(FLUSH):
case YY_STATE_EOF(HELP_COND):
case YY_STATE_EOF(RFILE_COND):
case YY_STATE_EOF(REQ_COND):
case YY_STATE_EOF(SYS_COND):
case YY_STATE_EOF(RLABSCRIPT):
{ return REOF; }
	YY_BREAK
case 113:
YY_RULE_SETUP
ECHO;
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 356 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 356 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 355);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

/* **************************************************************
 * Process STRINGS before giving them to yyparse(). This piece of
 * code obtained from MAWK (GNU copylefted) by Mike Brennan.
 * However I have modified it so any bugs are my fault.
 * ************************************************************** */

#define  ET_END     9

static struct
{
  char in;
  char out;
} escape_test[ET_END+1] = {
  { 'n' , '\n' },
  { 't' , '\t' },
  { 'f' , '\f' },
  { 'b' , '\b' },
  { 'r' , '\r' },
  { 'a' , '\07' },
  { 'v' , '\013' },
  { '\\', '\\' },
  { '\"', '\"' },
  { 0 , 0 }
};

/* count '\n' in the string if it is multiline */
int count_eol(char *s)
{
  register char *p = s;
  int count=0;
  while (*p)
  {
    if (*p == '\n'){ ++count; }
    *p++;
  }

  return count;
}

/* process the escape characters in a string, in place . */
char * rm_escape(char *s)
{
  register char *p, *q ;
  int i ;

  q = p = s ;

  while ( *p )
  {
    if ( *p == '\\' )
    {
      escape_test[ET_END].in = * ++p ;
      i = 0 ;
      while ( escape_test[i].in != *p )  i++ ;
      if ( i != ET_END )
      {
        p++ ; *q++ = escape_test[i].out ;
      }
      else if ( *p == 0 )
        *q++ = '\\' ;
      else
	    {
	      *q++ = '\\' ; *q++ = *p++ ;
	    }
    }
    else
    {
      *q++ = *p++ ;
    }
  }
  *q = 0 ;
  return s;
}

/* **************************************************************
 * Set the input function pointer from an external source file.
 * ************************************************************** */
void set_rlab_input (int type)
{
  if (type == 0)
  {
    /* Read from stdin */
    rinput = (RINPUT) rlab_yy_input;
  }
  else
  {
    /* Read from a character string */
    rinput = (RINPUT) rlab_string_input;
  }
}

#ifdef HAVE_READLINE
char *do_gets (char *line, char *prompt);
extern char *readline (char *prompt);
extern void add_history (char *string);
#endif

#ifdef HAVE_INPUT_EDIT
char  *do_gets (char *line, char *prompt);
extern char *getline (char *prompt);
extern void gl_histadd (char *string);
#endif

/* **************************************************************
 * Get input for flex scanner
 * ************************************************************** */
void rlab_yy_input(char *buf, int *result, int *max_size)
{
  char *prmpt;
  int write_diary;

  write_diary = get_write_diary ();

  signal (SIGINT, SIG_IGN);

  if (flush_line)
  {
    strcpy (buf, dummy_line);
    *result = strlen (buf);
    line_contents = buf;
    signal (SIGINT, intcatch_wait);
    return;
  }

  if(prompt)
    prmpt = prompt2;
  else
    prmpt = prompt1;

#if defined(HAVE_READLINE)  || defined(HAVE_INPUT_EDIT)
  if((yyin == stdin) && use_readline)
  {
    /* Interactive, using readline command editing */
    if(do_gets(buf, prmpt) == 0)
      *result = YY_NULL;
    else
      *result = strlen(buf);
    lineno = 0;
  }
  else if((yyin == stdin) && !use_readline)
  {
    /* Interactive, no readline */
    fprintf(stderr, prmpt);

    if((fgets(buf, *max_size, yyin)) == 0)
      *result = YY_NULL;
    else
      *result = strlen(buf);
    lineno = 0;
  }
#else
  if(yyin == stdin)
  {
    /* interactive, put out a prompt */
    fprintf(stderr, prmpt);
    if((fgets(buf, *max_size, yyin)) == 0)
      *result = YY_NULL;
    else
      *result = strlen(buf);
    lineno = 0;
  }
#endif  /* HAVE_READLINE || HAVE_INPUT_EDIT */
  else
  {
    if((fgets(buf, *max_size, yyin)) == NULL)
      *result  = YY_NULL;
    else
      *result = strlen(buf);
  }

  if(write_diary)
  {
    FILE *diary_file_ptr = get_diary_file_ptr ();
    fprintf(diary_file_ptr, "%s", buf);
  }
  else if (Rlab_Debug)
  {
    fprintf(stderr, "%i: %s", lineno, buf);
  }

  /* Set line_contents so parser can get it in case of parser error */
  line_contents = buf;

  signal(SIGINT, intcatch_wait);
}

extern char *eval_string;    /* bltin2.c */

/*
 * Give the scanner input from a character string.
 * eval_string is a global variable.
 * Note that we have to append a '\n' to each string.
 */

void rlab_string_input (char * buf, int * result, int * max_size)
{
  size_t eval_length;

  if (flush_line)
  {
    strcpy (buf, dummy_line);
    *result = strlen (buf);
    line_contents = buf;
    return;
  }

  if (eval_string == 0)
  {
    /* The string has already been handed to the scanner. */
    *result = YY_NULL;
    return;
  }

  eval_length = strlen (eval_string);
  if (eval_length < (*max_size - 1))
  {
    /* Copy the string ONCE */
    strcpy (buf, eval_string);
    strcat (buf, "\n");
    line_contents = buf;
    *result = strlen (buf);
    eval_string = 0;
  }
  else
  {
    /*
     * We are going to have to hand the scanner portions
     * of the eval_string.
     */
  }
}

#ifdef HAVE_READLINE
/* **************************************************************
 * Use GNU Readline library to provide command line editing.
 * Read a string, and return a pointer to it.
 * Returns NULL on EOF.
 * ************************************************************** */
char *do_gets(char * buf, char * prompt)
{
  static char *line_read = 0;
  char *tmp;
  int len;

  /*
   * If the buffer pool has already been allocated,
   * return the memory to the free pool.
   */

  if(line_read != 0)
  {
    free(line_read);
    line_read = 0;
  }

  /* Get a line from the user. */
  line_read = readline(prompt);

  /* If the line has any text in it, save it on the history. */
  if(line_read && *line_read)
    add_history(line_read);

  /* We must put the newline back on the end of line_read */
  if(line_read != 0)
  {
    len = strlen(line_read);
    tmp = GC_MALLOC(sizeof(char)*(len+2));
    if (tmp == 0)
      rerror ("out of memory");
    strcpy(tmp, line_read);
    tmp[len] = '\n';
    tmp[len+1] = '\0';

    /* Both this and the above statments need fixing */
    strcpy(buf, tmp);
    GC_FREE(tmp);
  }
  else
    buf = 0;

  return(buf);
}

#endif  /* HAVE_READLINE */
#ifdef HAVE_INPUT_EDIT

/* **************************************************************
 * Use input-edit library to provide command line editing.
 * Read a string, and return a pointer to it.
 * Returns NULL on EOF.
 * ************************************************************** */
char * do_gets(char *buf, char *prompt)
{
  char *tmp;

  tmp = getline(prompt);
  gl_histadd(tmp);
  if (*tmp != 0)
  {
    strcpy(buf, tmp);
  }
  else
  {
    buf = 0;
  }
  return buf;
}

#endif  /* HAVE_INPUT_EDIT */

static int lnstack[ FOPEN_MAX ];
static char *fnstack[ FOPEN_MAX ];
static FILE *fstack[ FOPEN_MAX ];
static int bptr = 0;

/* **************************************************************
 * Replacement yywrap().
 * Yywrap is called by scanner, when it thinks it is at end-of-input.
 * If yywrap returns 0, then it is assumed that the functions has
 * gone ahead and setup yyin to point to another input file. If
 * yywrap returns 1, then the scanner terminates, returning 0 to
 * it's caller.
 * ************************************************************** */
#undef  THIS_FUNCTION
#define THIS_FUNCTION "yywrap"
int yywrap(void)
{
  if(!new_file(0))
  {
    return(1);
  }

  return(0);
}

/* **************************************************************
 * Tell flex to read from another source. If called with a 0 ptr,
 * decrement the buffer. If called with a string, then try to open
 * the file and increment the buffer.
 * Return 1: if buffer is successfuly inc'ed, or dec'ed
 * Return 0: if unsuccessful
 * ************************************************************** */
#undef  THIS_FUNCTION
#define THIS_FUNCTION "new_file"
int new_file(char *file_name)
{
  static int once = 0;
  FILE *tmp=0;

  if(file_name != 0)
  {
    /* Check for stack over-run */
    if(bptr > FOPEN_MAX - 1)
    {
      fprintf(stderr, "ERROR: too many input files\n");
      return(0);
    }
    if(!strcmp("stdin", file_name))
    {
      yyin = stdin;
      fstack[bptr] = yyin;
    }
    else
    {
      /* Open new file, and point flex(1) at it */
      if((tmp = get_file_ds(file_name, "r", 0)) == 0)
      {
        fprintf(stderr, "ERROR: %s, cannot open for read\n", file_name);
        return(0);
      }
      else
      {
        yyin = tmp;
        fstack[bptr] = yyin;
      }
    }
    if(once)                 /* Why did I do this ? */
      yyrestart(yyin);
    else
      once = 1;

    /* Point cur_file_name to current input file */
    if (fnstack[bptr])
      GC_FREE(fnstack[bptr]);
    fnstack[bptr] = cpstr(file_name);
    if (curr_file_name)
      GC_FREE(curr_file_name);
    curr_file_name = cpstr(file_name);

    /* Save curent line number on stack */
    lnstack[bptr] = lineno;

    /* Now set lineno for new file */
    lineno = 1;

    bptr++;
    return(1);
  }
  else
  {
    /* Decrement to current file */
    bptr--;

    /* Close the old file */
    if (fstack[ bptr ] != stdin)
    {
      close_file_ds( fnstack[ bptr ] );
      GC_FREE(fnstack[bptr]);
      fnstack[bptr]=0;
    }

    /* Dec bptr again to point to the next file */
    bptr--;
    if( bptr >= 0 )
    {
      if (curr_file_name)
        GC_FREE(curr_file_name);
      curr_file_name = cpstr(fnstack[bptr]);
      yyin = fstack[bptr];
      yyrestart(yyin);
      /* lineno = lnstack[bptr+1] + 1; */
      lineno = lnstack[bptr+1];

      bptr++;    /* Inc the ptr for next call to new_file() */
    }
    else     /* We're out of files */
    {
      if( fstack[0] == stdin )
      {
        if (curr_file_name)
          GC_FREE(curr_file_name);
        curr_file_name = cpstr("stdin");
        yyin = stdin;
        yyrestart(yyin);
        /* lineno = lnstack[0] + 1; */
        lineno = lnstack[0];
        bptr = 1;
      }
      else
      {
        bptr = 0;
        /* lineno = lnstack[0] + 1; */
        lineno = lnstack[0];
      }
    }
    return(0);
  }
}

/*
 * Set the zero index FILEstack ptr to stdin.
 */

void set_input_stdin()
{
  yyin = stdin;
  fstack[0] = yyin;
}

/*
 * Call yyrestart in case of longjmp
 */
void rlab_yyrestart()
{
  yyrestart(yyin);
}

/* **************************************************************
 * Free up flex's input buffers.
 * ************************************************************** */
void scanner_cleanup()
{
  int i;

  for(i = 0; i < FOPEN_MAX; i++)
  {
    if (fnstack[i])
      GC_FREE(fnstack[i]);
    fnstack[i]=0;
  }
  if (curr_file_name)
    GC_FREE(curr_file_name);
  curr_file_name = 0;
}

