
#define SIZEOF_DOUBLE 8
#define SIZEOF_LONG_INT 4
#define SIZEOF_INT 4
#define SIZEOF_SHORT_INT 2
#define STDC_HEADERS 1
#define STDC_HEADERS 1
#define HAVE_DIRENT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_TIME_H 1
#define HAVE_FLOAT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define HAVE_VALUES_H 1
#define HAVE_FPU_CONTROL_H 1
#define HAVE_DIFFTIME 1
#define HAVE_RINDEX 1
#define HAVE_MATHERR 1
#define HAVE_GETENV 1
#define HAVE_PUTENV 1
#define HAVE_SLEEP 1
#define HAVE_LOGB 1
#define HAVE_ALLOCA_H 1
#define HAVE_ALLOCA 1
#define SVR4 1
#define HAVE_RINT_DEC 1
#define HAVE_RINT 1
#define SETUP_FPE 1
#define HAVE_TIMES 1
#define HAVE_CLOCK 1
#define HAVE_SYSCONF 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_TIMES_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_DLOPEN 1
#define HAVE_DLSYM 1
#define HAVE_DLCLOSE 1
#define HAVE_SO 1
#define HAVE_READLINE 1
#define HAVE_RLAB_PGPLOT 1
