      SUBROUTINE SETSTP(HTAN,IWORK,LIW,LRW,RWORK)
C
C***********************************************************************
C
C  Predictor stepsize computation.
C
C  THE FORMULAS UNDERLYING THE ALGORITHM ARE
C
C  ALPHLC=MAXIMUM OF ARCCOS(TL,TC) AND ALFMIN=2*ARCCOS(1-EPMACH)
C  HSEC  =NORM(XC-XF)
C  HSECL =NORM(XL-XC)
C  ABSNLC=ABS(SIN(.5*ALPHLC))
C  CURV  =LAST VALUE OF THE CURVATURE
C  CURVN =2*ABSNLC/HSEC
C  CORDIS=CORRECTOR DISTANCE TO CURRENT CONTINUATION POINT.
C           FORCE CORDIS TO LIE BETWEEN .01*HSEC AND HSEC.
C           UNLESS (CORDIS.EQ.0.0), BECAUSE THE PREDICTED POINT WAS
C           ACCEPTED.  IN SUCH A CASE, SET HTAN=HFACT*HSEC
C           INSTEAD OF USING FIRST ESTIMATE FOR HTAN.
C
C  THEN
C
C  CURVX=CURVN+HSEC*(CURVN-CURV)/(HSEC+HSECL)
C  A SIMPLER FORMULA IS USED IF WE DO NOT HAVE DATA AT TWO PREVIOUS
C  POINTS.
C
C  IF (IWORK(10).GE.2) CURVX MUST BE AT LEAST AS LARGE AS
C  THE MAXIMUM OF 0.001 AND .01/HSEC
C
C  FIRST ESTIMATE   (UNLESS (CORDIS.EQ.0.0) )
C
C  HTAN =SQRT(2*QUAL*CORDIS/CURVX)
C
C  ADJUSTED VALUE
C
C  HTAN=HTAN*(1.0+HTAN*(TC(IPC)-TL(IPC))/(2*HSEC*TC(IPC)))
C
C  READJUSTMENT AND TRUNCATIONS
C
C  IF STEPSIZE REDUCTION OCCURRED DURING LAST CORRECTOR PROCESS,
C  HTAN IS FORCED TO BE LESS THAN (HFACT-1)*HSEC/2.
C
C  HTAN MUST LIE BETWEEN (HSEC/HFACT) AND (HSEC*HFACT).
C  HTAN IS ALWAYS FORCED TO LIE BETWEEN USER SPECIFIED
C  MINIMUM AND MAXIMUM STEPS.
C
      DOUBLE PRECISION HALF
      DOUBLE PRECISION HUNDTH
      DOUBLE PRECISION ONE
      DOUBLE PRECISION THOUTH
      DOUBLE PRECISION TWO
      DOUBLE PRECISION ZERO
C
      PARAMETER (HALF=0.5)
      PARAMETER (HUNDTH=0.01)
      PARAMETER (ONE=1.0)
      PARAMETER (THOUTH=0.001)
      PARAMETER (TWO=2.0)
      PARAMETER (ZERO=0.0)
C
      INTRINSIC ABS
      INTRINSIC MAX
      INTRINSIC MIN
      INTRINSIC SIN
      INTRINSIC SQRT
C
      INTEGER   LIW
      INTEGER   LRW
C
      DOUBLE PRECISION CURV
      DOUBLE PRECISION CURVX
      DOUBLE PRECISION HTAN
      INTEGER   IWORK(LIW)
      DOUBLE PRECISION RWORK(LRW)
      DOUBLE PRECISION TEMP
      DOUBLE PRECISION TMP
C
      RWORK(11)=MAX(RWORK(10),RWORK(11))
C
C  COMPUTE NEW CURVATURE DATA
C
      CURV=RWORK(16)
      RWORK(16)=TWO*ABS(SIN(HALF*RWORK(11)))/RWORK(21)
      IF(CURV.EQ.ZERO)CURV=RWORK(16)
      CURVX=RWORK(16)
      IF(RWORK(22).NE.ZERO)CURVX=
     1 RWORK(16)+RWORK(21)*(RWORK(16)-CURV)/(RWORK(21)+RWORK(22))
      TMP=MAX(THOUTH,(HUNDTH)/RWORK(21))
      CURVX=MAX(CURVX,TMP)
C
C  IF CONVERGENCE DISTANCE IS ZERO, SET ESTIMATE TO HFACT*HSEC.
C  ELSE TRUNCATE QUAL*CORDIS TO LIE BETWEEN .01*HSEC AND HSEC.
C
      HTAN=RWORK(20)*RWORK(21)
      IF(RWORK(15).NE.ZERO)THEN
        TEMP=MAX(RWORK(23)*RWORK(15),HUNDTH*RWORK(21))
        TEMP=MIN(TEMP,RWORK(21))
        HTAN=SQRT(TWO*TEMP/CURVX)
        ENDIF
C
C  Adjust the step to account for estimated curvature in the direction
C  of the parameter.
C
      IF(IWORK(18).GT.0)
     * HTAN=MIN(HTAN,HALF*(RWORK(20)-ONE)*RWORK(21))
      IF(IWORK(3).NE.1)THEN
        TEMP=ONE+(ONE-RWORK(25)/RWORK(24))*(HALF*HTAN)/RWORK(21)
        HTAN=HTAN*TEMP
        ENDIF
C
C  Enforce restrictions on growth and size of the step.
C
      HTAN=MAX(HTAN,RWORK(21)/RWORK(20))
      HTAN=MIN(HTAN,RWORK(21)*RWORK(20))
      HTAN=MAX(HTAN,RWORK(3))
      HTAN=MIN(HTAN,RWORK(4))
      RETURN
      END
