#!/bin/sh

sh ./configure \
  --rlab2 \
  --with-im \
  --with-arpack \
  --with-gphoto2 \
  --enable-python \
  --enable-glpk \
  --enable-sqlite \
  --with-plplot \
  --with-flex \
  --with-bison \
  $*

make scanner


